// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwwpegesoehlicfvzjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3d3BlZ2Vzb2VobGljZnZ6anNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzA5ODQsImV4cCI6MjA3MTk0Njk4NH0.56w9xGLAuGqvbMaQAGoxTHH7_BEPLznqeGfY0K_aHe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});